
[env]
TERM = "xterm-256color"

[font]
size = 13
offset = { x = 0, y = 0 }
# normal.family = "MesloLGS NF"
# normal.family = "CommitMono Nerd Font Mono"
normal.family = "Maple Mono Normal NF CN"

[window]
blur = true
opacity = 0.7
padding = { x = 10, y = 10 }
decorations = "Buttonless"
option_as_alt = "Both"

[keyboard]
bindings = [
  { key = "Left", mods = "Alt", chars = "\u001BB" },
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Enter", mods = "Command", action = "ToggleMaximized" },
  { key = "C", mods = "Command|Shift", action = "ToggleViMode" },
]

[general]
import = [
  "~/.config/alacritty/themes/wombat.toml"
]

# [shell]
# program = "/opt/homebrew/bin/zellij"
