# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ':espanso'
    replace: 'Hi there!'

  - trigger: ':ai-trans'
    replace: '以下我將使用 "A|B" 的方式進行提問，A 為我的中文原意，B 為我嘗試將 A 翻譯為英文，希望你可以修正我的 B 翻譯內容，讓他更符合英文母語者與科技業者常使用的語句，除此之外，希望你能再提供我，在不參考 B 的情況下，你會如何翻譯 A'

  - trigger: ':ai-plan-ending'
    replace: '以上需求為我的想法，請確認可行性以及思考是否有任何疑慮或疑問可以向我提出，以確保雙方達成共識後再進行實作。'

  - trigger: ':ai-impl-git-rule'
    replace: '過程中請依照原子性原則進行提交，以確保程式可複驗及必要時的回朔。'

  - trigger: ':ai-impl-tdd-rule'
    replace: '過程中請遵循 tdd 原則進行規劃、測試、實作、驗證等流程確保程式碼品質與交付結果的穩定性與可驗證性。'

  - trigger: ':ai-impl-container-rule'
    replace: '過程中若需要執行任何命令，請優先使用 podman compose exec 為前綴在 container 中運行，若真的有需要在本機執行，請向我提出請求。'
