# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ':espanso'
    replace: 'Hi there!'

  - trigger: ':ai-generate-git-message'
    replace: '{{output}}'
    vars:
      - name: form_data
        type: form
        params:
          layout: |
            更新說明: [[current_change]]
          fields:
            current_change:
              multiline: true
      - name: output
        type: shell
        params:
          cmd: |
            CURRENT_CHANGE="{{form_data.current_change}}"

            if [[ -n $CURRENT_CHANGE ]]; then
              echo "本次調整為，$CURRENT_CHANGE。"
            fi

  - trigger: ':ai-generate-git-message'
    replace: '{{output}}'
    vars:
      - name: form_data
        type: form
        params:
          layout: |
            暫存檔案: [[git_status]]
          fields:
            git_status:
              multiline: true
      - name: output
        type: shell
        params:
          cmd: |
            GIT_STATUS="{{form_data.git_status}}"

            if [[ -n $GIT_STATUS ]]; then
              echo "我已經將需要的檔案 git add 加入暫存的變更中，請基於上面的描述以及暫存變更的內容產生合適的 git commit 提交訊息並以英文描述，待我確認完畢後會自行提交

              git diff --staged --name-status
              $GIT_STATUS"
            fi
