return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    opts = {
      ensure_installed = {
        "c",
        "lua",
        "vim",
        "vimdoc",
        "javascript",
        "typescript",
        "tsx",
        "json",
        "html",
        "css",
        "bash",
        "query",
        "markdown",
        "markdown_inline",
        "blade",
        "go",
        "php",
        "scss",
        "vue",
        "tmux",
        "sql",
        "rust",
      },
      auto_install = true,
      sync_install = false,
    },
  },
}
